name: flutter_application_proj2cp
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0   
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/images_entree/
    - assets/logo.png
    - assets/Ellipse.png
    - assets/icons/
